version: "3"

services:
    wordpress:
        build:
            context: ./bin/wordpress
        container_name: "wordpress"
        restart: "always"
        ports: 
            - 80:80
            - 443:80
        links:
            - mysql
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html
            - ${PHP_INI-./config/php}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
            - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    mysql:
        build: ./bin/mysql
        container_name: "mysql"
        restart: "always"
        ports:
            - 3306:3306
        volumes: 
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    